name: stackage-extras
version: 0.0.0.0
synopsis: Stacakge tool extras
description: ...
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: phadej/stackage-extras
category: Development
tested-with: GHC==7.10.3
extra-source-files:
- README.md

ghc-options: -Wall

dependencies:
- base >=4.7 && <4.9
- base-compat
- bytestring
- Cabal
- exceptions
- github
- transformers
- lens
- lens-aeson
- optparse-applicative
- packdeps
- http-client
- http-client-tls
- regex-applicative
- regex-applicative-text
- text
- vector
- yaml >=0.8.14

executables:
  stackage-extras:
    main: Main.hs
    source-dirs: src
